// 2026 新托福 Practice Pack 6 — Reading Section

export const pack6 = {
  id: 'pack6',
  name: 'Practice Pack 6',
  modules: [
    // ═══ Module 1 ═══
    {
      id: 'pack6-m1',
      name: 'Module 1',
      time: 11 * 60 + 30,
      sections: [
        // --- Complete the Words ---
        {
          type: 'complete_words',
          id: 'pack6-m1-cw',
          title: 'Rain and Ecosystems',
          instructions: 'Fill in the missing letters in the paragraph.',
          paragraph: [
            { text: 'Rain is a crucial part of Earth\'s ecosystem, supporting both plant growth and animal survival.  As ' },
            { blank: 'itation', prefix: 'precip', answer: 'precipitation' },
            { text: ' falls ' },
            { blank: 'om', prefix: 'fr', answer: 'from' },
            { text: ' ' },
            { blank: 'ky', prefix: 'the s', answer: 'the sky' },
            { text: ', it ' },
            { blank: 'nishes', prefix: 'reple', answer: 'replenishes' },
            { text: ' water ' },
            { blank: 'rces', prefix: 'sou', answer: 'sources' },
            { text: ', nourishes ' },
            { blank: 'ation', prefix: 'veget', answer: 'vegetation' },
            { text: ', and ' },
            { blank: 'ains', prefix: 'sust', answer: 'sustains' },
            { text: ' wildlife.  Some ' },
            { blank: 'ions', prefix: 'reg', answer: 'regions' },
            { text: ' receive ' },
            { blank: 'dant', prefix: 'abun', answer: 'abundant' },
            { text: ' rainfall, ' },
            { blank: 'ile', prefix: 'wh', answer: 'while' },
            { text: ' others experience prolonged dry periods, affecting local environments.  Excessive rain can lead to floods, creating hazards for communities and natural habitats.  Despite occasional dangers, rainfall is essential for maintaining ecological balance, ensuring that plants and animals thrive in diverse climates around the world.' },
          ],
        },

        // --- Read in Daily Life: Maria's Email ---
        {
          type: 'daily_life',
          id: 'pack6-m1-dl1',
          title: 'Assignment Extension Request',
          material_type: 'email',
          material: {
            subject: 'Assignment Extension Request',
            from: 'Maria',
            to: 'Professor Kim',
            body: "Dear Professor Kim,\n\nI'm writing to request a two-day extension for the research paper. My laptop crashed and I lost three days of work. I have already started rewriting and can submit by Friday. Thank you for considering my request.\n\nBest regards,\nMaria",
          },
          questions: [
            {
              id: 11,
              text: 'What does Maria\'s mention of having "already started rewriting" suggest about her attitude?',
              options: [
                'Maria expects the professor to automatically approve her request.',
                'Maria is trying to make the professor feel sorry for her situation.',
                'Maria believes technical problems excuse students from meeting deadlines.',
                'Maria is taking responsibility and showing effort to complete the work.',
              ],
              correct: 3,
              question_type: 'inference',
              explanation: 'By mentioning she has "already started rewriting," Maria demonstrates proactive effort rather than passivity. She is not just explaining a problem — she is showing she is actively working toward a solution, which signals responsibility.',
            },
            {
              id: 12,
              text: 'What is Maria asking for?',
              options: [
                'Help recovering her lost computer files',
                'Additional time to complete an assignment',
                'Permission to submit a shorter research paper',
                'Technical support for her laptop problems',
              ],
              correct: 1,
              question_type: 'detail',
              explanation: 'Maria explicitly writes "I\'m writing to request a two-day extension for the research paper." She is asking for more time, not file recovery, a shorter paper, or tech support.',
            },
          ],
        },

        // --- Read in Daily Life: Heating Maintenance ---
        {
          type: 'daily_life',
          id: 'pack6-m1-dl2',
          title: 'Heating System Maintenance',
          material_type: 'email',
          material: {
            subject: 'Upcoming Heating System Maintenance – Tuesday, May 27',
            from: 'Robert Thompson',
            to: 'Ms. Gardner',
            body: "Dear Ms. Gardner,\n\nI hope you're doing well. I'm writing to inform you of a scheduled maintenance procedure on the office heating system, set to take place on Tuesday, May 27, from 8:00 A.M. to 5:00 P.M. This essential work is part of our seasonal inspection and efficiency upgrade initiative to ensure optimal performance during the colder months.\n\nPlease note that the heating system will be offline throughout the day, and indoor temperatures will drop noticeably. We recommend dressing in warm layers and advising your team to do the same. If any team members are particularly sensitive to cooler environments, remote work arrangements may be considered.\n\nAdditionally, as external technicians will be on-site, please ensure all confidential materials are secured appropriately.\n\nShould you have any questions, contact the maintenance team at 555-7264.\n\nWarm regards,\nRobert Thompson",
          },
          questions: [
            {
              id: 13,
              text: 'What is indicated about the office heating system?',
              options: [
                'It failed an inspection.',
                'It will not be functioning during maintenance.',
                'It is not working properly.',
                'It performs optimally.',
              ],
              correct: 1,
              question_type: 'detail',
              explanation: 'The email states "the heating system will be offline throughout the day." This directly indicates it will not be functioning during maintenance. There is no mention of it having failed an inspection or not working properly — the maintenance is scheduled and preventive.',
            },
            {
              id: 14,
              text: 'What can be inferred about the weather on May 27?',
              options: [
                'It will be cooler than the temperature at which the office is normally kept.',
                'It will be unusual for the season.',
                'It will require office workers to stay home rather than going to the office.',
                'It will change throughout the day.',
              ],
              correct: 0,
              question_type: 'inference',
              explanation: 'The email says "indoor temperatures will drop noticeably" when the heating is off, and recommends "dressing in warm layers." This implies the outdoor/unheated temperature is cooler than the office is normally kept. Remote work is only "considered" for sensitive employees, not required for everyone.',
            },
            {
              id: 15,
              text: 'Who will be performing maintenance?',
              options: [
                'Ms. Gardner',
                'Ms. Gardner\'s team members',
                'Professionals from another company',
                'Robert Thompson',
              ],
              correct: 2,
              question_type: 'detail',
              explanation: 'The email mentions "external technicians will be on-site," meaning professionals from outside the company. Robert Thompson is the sender, not the maintenance worker, and Ms. Gardner\'s team is asked to secure confidential materials, not perform repairs.',
            },
          ],
        },

        // --- Read an Academic Passage: Fungi ---
        {
          type: 'academic_passage',
          id: 'pack6-m1-ap',
          title: 'The Role of Fungi in Ecosystems',
          passage: `Fungi play a crucial role in ecosystems, often working behind the scenes to decompose organic matter and recycle nutrients. Unlike plants, fungi do not photosynthesize; instead, they obtain energy by breaking down dead plants and animals. This decomposition process is essential for nutrient cycling, as it releases vital elements like nitrogen and phosphorus back into the soil, supporting new plant growth. Their role in nutrient cycling is indispensable for healthy ecosystems.

One fascinating group of fungi is mycorrhizal fungi, which form symbiotic relationships with plant roots. These fungi extend the root system of plants, allowing them to access water and nutrients more efficiently. In return, the plants provide the fungi with carbohydrates produced through photosynthesis. This mutually beneficial relationship enhances plant growth and resilience, particularly in nutrient-poor soils.

Not all fungi are beneficial. Some pathogenic fungi cause diseases in plants and animals, leading to significant agricultural and ecological impacts. For example, the chytrid fungus has devastated amphibian populations worldwide. Understanding the diverse roles of fungi in ecosystems can help scientists develop strategies to mitigate their negative effects while leveraging their benefits for environmental sustainability.`,
          questions: [
            {
              id: 16,
              paragraph: 1,
              text: 'According to the passage, fungi are beneficial to plants in terms of',
              options: [
                'helping plants to decompose organic matter',
                'making it possible for plants to photosynthesize',
                'reducing the amount of nitrogen and phosphorus inside plants',
                'helping plants to obtain nutrients',
              ],
              correct: 3,
              question_type: 'detail',
              explanation: 'Paragraph 2 describes mycorrhizal fungi that "extend the root system of plants, allowing them to access water and nutrients more efficiently." This directly supports option D. Fungi decompose matter themselves (not helping plants do it), and the passage says fungi don\'t photosynthesize.',
            },
            {
              id: 17,
              paragraph: 0,
              text: 'The word "indispensable" in the passage is closest in meaning to',
              options: [
                'similar',
                'well-known',
                'essential',
                'useful',
              ],
              correct: 2,
              question_type: 'vocab',
              highlighted_word: 'indispensable',
              explanation: '"Indispensable" means absolutely necessary or essential — something you cannot do without. The sentence says fungi\'s role "is indispensable for healthy ecosystems," meaning it is essential/required. "Useful" is too weak; "similar" and "well-known" are unrelated.',
            },
            {
              id: 18,
              paragraph: null,
              text: 'Which of the following is NOT mentioned in the passage as a process performed by fungi?',
              options: [
                'Decomposing organic matter',
                'Releasing nitrogen and phosphorus into the soil',
                'Forming important relationships with plant roots',
                'Producing their own food',
              ],
              correct: 3,
              question_type: 'negative_fact',
              explanation: 'The passage explicitly states fungi "do not photosynthesize" — they cannot produce their own food. All other options are directly mentioned: decomposing organic matter (P1), releasing nitrogen/phosphorus (P1), and forming relationships with plant roots (P2).',
            },
            {
              id: 19,
              paragraph: 2,
              text: 'What can be inferred about the diverse roles of fungi?',
              options: [
                'This diversity makes fungi especially difficult for scientists to understand.',
                'This diversity is considered to be important for the ongoing health of the environment.',
                'This diversity will decline when harmful fungi are eliminated.',
                'This diversity has been linked to the sustainability of amphibian populations.',
              ],
              correct: 1,
              question_type: 'inference',
              explanation: 'The passage concludes that understanding fungi\'s diverse roles can help "leveraging their benefits for environmental sustainability." This implies their diversity is important for environmental health. The chytrid fungus devastated amphibians — fungi diversity isn\'t linked to amphibian sustainability.',
            },
            {
              id: 20,
              paragraph: 1,
              text: 'What can be inferred about mycorrhizal fungi?',
              options: [
                'They compete with plants for carbohydrates.',
                'They help plants absorb nutrients.',
                'They decompose dead plants and animals.',
                'They can cause diseases in plants.',
              ],
              correct: 1,
              question_type: 'inference',
              explanation: 'Paragraph 2 says mycorrhizal fungi "extend the root system of plants, allowing them to access water and nutrients more efficiently." This means they help plants absorb nutrients. They receive carbohydrates from plants (not compete for them). Decomposition and disease are roles of other fungi types.',
            },
            {
              id: 22,
              paragraph: 1,
              text: 'Look at the four squares [■] that indicate where the following sentence could be added to the passage. Where would the sentence best fit?',
              insert_sentence: 'Unlike most surface roots, these fungal extensions can reach far into the soil, accessing pockets of water and minerals that would otherwise be unavailable to the plant.',
              insertion_points: [
                'One fascinating group',
                'These fungi extend',
                'In return',
                'This mutually beneficial',
              ],
              options: ['■A', '■B', '■C', '■D'],
              correct: 2,
              question_type: 'text_insertion',
              explanation: 'Position C (before "In return") is best. The insert sentence explains HOW the fungi reach deeper resources — a detail that logically follows the general claim that fungi "extend the root system" (sentence 2) and precedes the exchange relationship ("In return, the plants provide carbohydrates", sentence 3). Positions A and B are too early; the sentence needs the context of mycorrhizal fungi. Position D breaks up the summary statement.',
            },
            {
              id: 21,
              paragraph: 0,
              text: 'Which of the following best expresses the essential information in the highlighted sentence? Incorrect choices change the meaning or leave out essential information.',
              highlighted_word: 'This decomposition process is essential for nutrient cycling, as it releases vital elements like nitrogen and phosphorus back into the soil, supporting new plant growth.',
              options: [
                'Nutrient cycling by plants releases nitrogen and phosphorus, which fungi then use to decompose organic matter.',
                'The breakdown of organic matter by fungi returns key nutrients to the soil, helping new plants grow.',
                'Fungi must absorb nitrogen and phosphorus from the soil before they can begin the decomposition process.',
                'Because plants need nitrogen and phosphorus, fungi decompose soil to create space for new plant roots.',
              ],
              correct: 1,
              question_type: 'sentence_simplification',
              explanation: 'The original sentence has two parts: (1) fungi decompose organic matter, and (2) this releases nitrogen/phosphorus into the soil, which supports plant growth. Option B captures both parts accurately. Option A reverses who does the cycling. Option C misrepresents fungi as absorbing rather than releasing nutrients. Option D invents a claim about creating space for roots.',
            },
          ],
        },
      ],
    },

    // ═══ Module 2 ═══
    {
      id: 'pack6-m2',
      name: 'Module 2',
      time: 9 * 60,
      sections: [
        // --- Complete the Words ---
        {
          type: 'complete_words',
          id: 'pack6-m2-cw',
          title: 'Volcanoes',
          instructions: 'Fill in the missing letters in the paragraph.',
          paragraph: [
            { text: 'Volcanoes are openings in Earth\'s crust through which molten rock, ash, and gases are ejected.  Volcanic ' },
            { blank: 'tions', prefix: 'erup', answer: 'eruptions' },
            { text: ' can ' },
            { blank: 'ate', prefix: 'cre', answer: 'create' },
            { text: ' islands, ' },
            { blank: 'tains', prefix: 'moun', answer: 'mountains' },
            { text: ', and ' },
            { blank: 'her', prefix: 'ot', answer: 'other' },
            { text: ' landforms, but ' },
            { blank: 'ey', prefix: 'th', answer: 'they' },
            { text: ' can ' },
            { blank: 'so', prefix: 'al', answer: 'also' },
            { text: ' be ' },
            { blank: 'uctive', prefix: 'destr', answer: 'destructive' },
            { text: ', causing ' },
            { blank: 'age', prefix: 'dam', answer: 'damage' },
            { text: ' to ' },
            { blank: 'by', prefix: 'near', answer: 'nearby' },
            { text: ' areas.  ' },
            { blank: 'ying', prefix: 'Stud', answer: 'Studying' },
            { text: ' volcanoes helps scientists understand Earth\'s internal processes: for example, how volcanoes form at tectonic plate boundaries or over hotspots in the mantle and how magma rises up from the mantle and erupts as lava on the surface.' },
          ],
        },

        // --- Read in Daily Life: Community Solar Program ---
        {
          type: 'daily_life',
          id: 'pack6-m2-dl1',
          title: 'Community Solar Enrollment',
          material_type: 'email',
          material: {
            subject: 'Invitation to Join the Maplewood Community Solar Program',
            from: 'Green Horizons Energy',
            to: 'Maplewood Residents',
            body: "Dear Maplewood Resident,\n\nWe are pleased to invite you to enroll in the Maplewood Community Solar Program, launching this spring. By joining, you can access locally generated solar electricity without installing any equipment on your property.\n\nParticipants receive a monthly credit on their utility bill based on their share of the solar array's output. Average savings are estimated at 10–15% per year. Enrollment is free, and there are no cancellation fees if you move or change your mind within the first 60 days.\n\nSpaces are limited. Please return the enclosed enrollment form by April 30 or visit greenhorizons.com/maplewood to sign up online.\n\nWarm regards,\nGreen Horizons Energy",
          },
          questions: [
            {
              id: 19,
              text: 'What is one benefit of joining the program mentioned in the email?',
              options: [
                'Free solar panels installed on your home',
                'A reduction in monthly electricity bills',
                'Guaranteed electricity during power outages',
                'Priority access to city energy subsidies',
              ],
              correct: 1,
              question_type: 'detail',
              explanation: 'The email states participants receive "a monthly credit on their utility bill," resulting in estimated savings of 10–15% per year — a reduction in electricity bills. Installing panels on your home, outage protection, and subsidy priority are not mentioned.',
            },
            {
              id: 20,
              text: 'What can be inferred about residents who enroll but then move within the first two months?',
              options: [
                'They will be required to pay a cancellation fee.',
                'They can leave the program without financial penalty.',
                'They must transfer their enrollment to the new resident.',
                'They will lose any bill credits they have already received.',
              ],
              correct: 1,
              question_type: 'inference',
              explanation: 'The email explicitly states "there are no cancellation fees if you move or change your mind within the first 60 days." 60 days equals approximately two months, so residents who move within that period can exit the program at no cost.',
            },
          ],
        },

        // --- Read in Daily Life: Office Energy Policy ---
        {
          type: 'daily_life',
          id: 'pack6-m2-dl2',
          title: 'Office Energy Conservation Policy',
          material_type: 'email',
          material: {
            subject: 'New Office Energy Conservation Guidelines – Effective Monday',
            from: 'Facilities Management',
            to: 'All Staff',
            body: "Dear Team,\n\nAs part of our commitment to reducing the building's carbon footprint, Facilities Management is introducing the following energy conservation guidelines, effective this Monday:\n\n1. Computers and monitors must be shut down — not merely put to sleep — at the end of each workday.\n2. Lights in meeting rooms should be turned off when not in use. Motion-sensor lights have been installed in Rooms 3A and 3B.\n3. The air conditioning setpoint has been raised from 21°C to 23°C during summer months. Personal desk fans are permitted.\n4. Staff are encouraged to use the stairs for floors 1–4 to reduce elevator energy use.\n\nThese measures are expected to cut the building's electricity consumption by approximately 12%. Compliance will be tracked quarterly, and departments that meet targets will be recognized in the company newsletter.\n\nThank you for your cooperation.\nFacilities Management",
          },
          questions: [
            {
              id: 21,
              text: 'According to the email, what change has been made to Rooms 3A and 3B?',
              options: [
                'The air conditioning setpoint has been lowered.',
                'The rooms have been converted into storage areas.',
                'Lighting has been automated with motion sensors.',
                'Computers in those rooms must now be fully shut down.',
              ],
              correct: 2,
              question_type: 'detail',
              explanation: 'The email states "Motion-sensor lights have been installed in Rooms 3A and 3B." This means the lighting in those rooms is now automated — it turns on or off based on detected movement.',
            },
            {
              id: 22,
              text: 'What is indicated about the new air conditioning policy?',
              options: [
                'Personal cooling devices are prohibited under the new policy.',
                'The change applies to all seasons equally.',
                'Staff may use personal fans to compensate for the warmer setting.',
                'The setpoint was previously set to 23°C.',
              ],
              correct: 2,
              question_type: 'detail',
              explanation: 'The email raises the A/C setpoint to 23°C during summer and adds "Personal desk fans are permitted," meaning staff can use fans to stay comfortable. Fans are permitted, not prohibited. The change only applies to summer months, not all seasons. The previous setpoint was 21°C, not 23°C.',
            },
            {
              id: 23,
              text: 'What can be inferred about how compliance will be monitored?',
              options: [
                'Individual employees will be penalized for violations.',
                'The building will undergo daily inspections by Facilities Management.',
                'Progress will be assessed on a team basis every three months.',
                'Results will only be shared with department heads.',
              ],
              correct: 2,
              question_type: 'inference',
              explanation: '"Compliance will be tracked quarterly, and departments that meet targets will be recognized" implies that performance is measured at the department level every quarter (three months). Penalizing individuals, daily inspections, and restricted reporting are not mentioned.',
            },
          ],
        },

        // --- Read an Academic Passage: Renewable Energy ---
        {
          type: 'academic_passage',
          id: 'pack6-m2-ap',
          title: 'Renewable Energy Sources',
          passage: `Renewable energy sources, such as solar, wind, and hydroelectric power, are increasingly gaining attention as alternatives to fossil fuels. Solar panels convert sunlight into electricity, providing a clean and abundant energy source. Wind turbines harness the power of wind, while hydroelectric plants use flowing water to generate electricity. These technologies offer significant environmental benefits, including reduced greenhouse gas emissions and decreased reliance on non-renewable resources.

However, renewable energy is not without its challenges. Solar and wind energy are intermittent, meaning they can be inconsistent depending on weather conditions. This intermittency requires the development of advanced storage solutions to ensure a steady supply of electricity. Additionally, the initial cost of installing renewable energy infrastructure can be high, although long-term savings and environmental benefits often outweigh this investment.

Recent innovations are addressing these issues. For instance, researchers are developing more efficient solar panels and energy storage systems that can store excess power generated during peak times. Wind turbines are being designed to operate in lower wind speeds, increasing their efficiency. Governments and private companies are also investing in renewable energy projects, recognizing the importance of transitioning to sustainable energy sources.`,
          questions: [
            {
              id: 11,
              paragraph: 0,
              text: 'Which of the following is mentioned in the passage as one environmental benefit of renewable energy sources?',
              options: [
                'They lower the amount of greenhouse gas produced.',
                'They provide a steady supply of electricity.',
                'They are easy to install.',
                'They can operate in all weather conditions.',
              ],
              correct: 0,
              question_type: 'detail',
              explanation: 'Paragraph 1 explicitly lists "reduced greenhouse gas emissions" as an environmental benefit. A "steady supply" is actually a challenge (paragraph 2 discusses intermittency). The passage never says they are easy to install or work in all weather.',
            },
            {
              id: 12,
              paragraph: 1,
              text: 'What challenge is associated with solar and wind energy?',
              options: [
                'High greenhouse gas emissions',
                'Inconsistent energy production',
                'Excessive reliance on fossil fuels',
                'Limited technological development',
              ],
              correct: 1,
              question_type: 'detail',
              explanation: 'Paragraph 2 states solar and wind energy "are intermittent, meaning they can be inconsistent depending on weather conditions." This directly matches "inconsistent energy production." Renewable energy reduces greenhouse gas emissions, not increases them.',
            },
            {
              id: 13,
              paragraph: 2,
              text: 'How are researchers addressing the issue of energy intermittency?',
              options: [
                'By developing more efficient solar panels',
                'By decreasing the cost of installation',
                'By using fossil fuels as a backup',
                'By limiting the use of renewable energy',
              ],
              correct: 0,
              question_type: 'detail',
              explanation: 'Paragraph 3 says "researchers are developing more efficient solar panels and energy storage systems." While storage directly addresses intermittency, the question asks about researchers\' approach, and developing better solar panels is explicitly mentioned. Fossil fuel backup and limiting use are never discussed.',
            },
            {
              id: 14,
              paragraph: 0,
              text: 'The word "reliance" in the passage is closest in meaning to',
              options: [
                'dependence',
                'trust',
                'use',
                'production',
              ],
              correct: 0,
              question_type: 'vocab',
              highlighted_word: 'reliance',
              explanation: '"Reliance" means the state of depending on something. "Decreased reliance on non-renewable resources" means reduced dependence on them. While "trust" is a related sense of the word, in this context it refers to dependence/need, not confidence.',
            },
            {
              id: 15,
              paragraph: 2,
              text: 'What is the author\'s purpose in mentioning "recent innovations"?',
              options: [
                'To highlight the drawbacks of renewable energy',
                'To suggest that fossil fuels are still necessary',
                'To describe solutions to the challenges of renewable energy',
                'To argue that the cost of renewable energy is too high',
              ],
              correct: 2,
              question_type: 'purpose',
              highlighted_word: 'Recent innovations',
              explanation: 'Paragraph 3 opens with "Recent innovations are addressing these issues" — "these issues" refers to the challenges discussed in paragraph 2 (intermittency and cost). The purpose is to show that solutions exist, not to criticize renewable energy or promote fossil fuels.',
            },
            {
              id: 16,
              paragraph: null,
              text: 'According to the passage, which of the following is NOT mentioned as a method of generating renewable energy?',
              options: [
                'Converting sunlight into electricity',
                'Harnessing the power of wind',
                'Using nuclear reactions to produce heat',
                'Using flowing water to generate electricity',
              ],
              correct: 2,
              question_type: 'negative_fact',
              explanation: 'The passage mentions solar panels (sunlight), wind turbines (wind), and hydroelectric plants (flowing water) as renewable energy methods. Nuclear reactions are never mentioned in the passage — nuclear power is not classified as renewable energy in the text.',
            },
            {
              id: 18,
              paragraph: 1,
              text: 'Look at the four squares [■] that indicate where the following sentence could be added to the passage. Where would the sentence best fit?',
              insert_sentence: 'Battery technology, for instance, has recently become more affordable and efficient, making large-scale energy storage increasingly viable.',
              insertion_points: [
                'However, renewable energy',
                'Solar and wind energy',
                'This intermittency requires',
                'Additionally, the initial cost',
              ],
              options: ['■A', '■B', '■C', '■D'],
              correct: 3,
              question_type: 'text_insertion',
              explanation: 'Position D (before "Additionally") is best. The insert sentence gives a specific example of a storage solution — it logically follows the sentence stating that "advanced storage solutions" are needed (position C\'s paragraph) and provides a concrete example before the passage moves on to discuss costs. Position A is too early (before challenges are introduced). Position B interrupts the definition of intermittency. Position C would separate "intermittency" from its storage solution context.',
            },
            {
              id: 17,
              paragraph: 1,
              text: 'Which of the following best expresses the essential information in the highlighted sentence? Incorrect choices change the meaning or leave out essential information.',
              highlighted_word: 'Solar and wind energy are intermittent, meaning they can be inconsistent depending on weather conditions.',
              options: [
                'Solar and wind power will eventually be replaced by energy sources that are not affected by weather.',
                'Because weather affects how much power solar and wind sources produce, their output is not always steady.',
                'The intermittency of renewable energy has caused governments to invest in fossil fuel alternatives.',
                'Solar and wind energy generate inconsistent levels of pollution depending on current weather conditions.',
              ],
              correct: 1,
              question_type: 'sentence_simplification',
              explanation: 'The original sentence states that solar and wind energy output varies based on weather (intermittent = inconsistent). Option B captures this accurately: weather affects output, making it unsteady. Option A introduces replacement by other sources, which is not stated. Option C inverts the relationship and brings in fossil fuels incorrectly. Option D misrepresents "inconsistent" as referring to pollution levels.',
            },
          ],
        },
      ],
    },
  ],
};
